import prettier from "prettier";

const fileheader = `
/**
 * This file is auto-generated by the @nancyjs/registry package.
 */`;
export const writeTsFile = async (
  path: string,
  content: string
) => {
  const formatted = await prettier.format(
    [fileheader, content].join("\n"),
    {
      parser: "typescript",
      printWidth: 30,
    }
  );
  return await Bun.write(path, formatted);
};
