/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "8ball",
  displayName: "8ball",
  website:
    "https://8ball.info/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/8ball/images/8ball.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/8ball/images/8ball.svg",
  },
  repository:
    "https://secp256k1.net/8ball.git",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/8ball",
        "https://rpc.8ball.info/",
        "https://rpc.8ball.nodestake.top",
        "https://8ball-rpc.genznodes.dev/",
        "https://rpc-8ball.comunitynode.my.id",
        "https://rpc-8ball.nodine.id",
        "https://rpc.8ball.nodexcapital.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/8ball",
        "https://rest.8ball.info",
        "https://api.8ball.nodestake.top",
        "https://8ball-api.genznodes.dev/",
        "https://api-8ball.comunitynode.my.id",
        "https://api-8ball.nodine.id/",
        "https://rest.8ball.nodexcapital.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-16",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-641",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
