/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "acrechain",
  displayName: "Acrechain",
  website:
    "https://arable.finance/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/acrechain/images/acre.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/acrechain/images/acre.svg",
  },
  repository:
    "https://github.com/ArableProtocol/acrechain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/acrechain",
        "https://rpc.acre.nodestake.top",
        "https://rpc-acre.d-stake.xyz",
        "https://rpc-acre.synergynodes.com",
        "https://acre-rpc.agoranodes.com",
        "https://acrechain-mainnet-rpc.autostake.com:443",
        "https://acre-rpc.genznodes.dev",
        "https://rpc.acre.tcnetwork.io",
        "https://mainnet-acre-rpc.konsortech.xyz",
        "https://acred-rpc.staketab.org:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/acrechain",
        "https://api-acre.d-stake.xyz",
        "https://lcd-acre.synergynodes.com",
        "https://acrechain-mainnet-lcd.autostake.com:443",
        "https://acre-rest.agoranodes.com",
        "https://acre-api.genznodes.dev",
        "https://rest.acre.tcnetwork.io",
        "https://mainnet-acre-api.konsortech.xyz",
        "https://acred-rest.staketab.org",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://jsonrpc-acre.d-stake.xyz",
        "https://rpc2-acre.synergynodes.com",
        "https://jsonrpc.acre.nodestake.top",
        "https://acre-rpc-evm.genznodes.dev/",
        "https://evm-acre.sr20de.xyz/",
        "https://evm.acrescan.com/",
        "https://json-rpc.acre.tcnetwork.io",
        "https://mainnet-acre-evm.konsortech.xyz",
      ],
    },
  },
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-490",
        order: "unordered",
        version: "ics20-1",
      },
      terra: {
        portId: "transfer",
        channelId:
          "channel-12",
        counterpartyChainId:
          "terra",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-69",
        order: "unordered",
        version: "ics20-1",
      },
      stargaze: {
        portId: "transfer",
        channelId:
          "channel-4",
        counterpartyChainId:
          "stargaze",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-121",
        order: "unordered",
        version: "ics20-1",
      },
      kujira: {
        portId: "transfer",
        channelId:
          "channel-7",
        counterpartyChainId:
          "kujira",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-47",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-8",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-457",
        order: "unordered",
        version: "ics20-1",
      },
      gravitybridge: {
        portId: "transfer",
        channelId:
          "channel-6",
        counterpartyChainId:
          "gravitybridge",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-106",
        order: "unordered",
        version: "ics20-1",
      },
      terra2: {
        portId: "transfer",
        channelId:
          "channel-9",
        counterpartyChainId:
          "terra2",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-77",
        order: "unordered",
        version: "ics20-1",
      },
      oraichain: {
        portId: "transfer",
        channelId:
          "channel-10",
        counterpartyChainId:
          "oraichain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-33",
        order: "unordered",
        version: "ics20-1",
      },
      evmos: {
        portId: "transfer",
        channelId:
          "channel-14",
        counterpartyChainId:
          "evmos",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-40",
        order: "unordered",
        version: "ics20-1",
      },
      stride: {
        portId: "transfer",
        channelId:
          "channel-13",
        counterpartyChainId:
          "stride",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-57",
        order: "unordered",
        version: "ics20-1",
      },
      axelar: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "axelar",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-51",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
