/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "agoric",
  displayName: "Agoric",
  website:
    "https://agoric.com/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/agoric/images/Agoric-logo-color.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/agoric/images/Agoric-logo-color.svg",
  },
  repository:
    "https://github.com/Agoric/agoric-sdk/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/agoric",
        "https://main.rpc.agoric.net:443",
        "https://agoric-rpc.polkachu.com",
        "https://rpc.agoric.nodestake.top",
        "https://agoric.rpc.kjnodes.com",
        "https://agoric-mainnet-rpc.autostake.com:443",
        "https://rpc-agoric-01.stakeflow.io",
        "https://agoric-rpc.0base.dev",
        "https://agoric.mellifera.network:26657",
        "https://agoric-rpc.stakeangle.com",
        "agoric-rpc.nodeasy.com:31531",
        "https://agoric-rpc.w3coins.io",
        "https://rpc.agoric.stakewith.us",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/agoric",
        "https://main.api.agoric.net:443",
        "https://api.agoric.nodestake.top",
        "https://agoric-api.polkachu.com",
        "https://agoric.api.kjnodes.com",
        "https://agoric-mainnet-lcd.autostake.com:443",
        "https://api-agoric-01.stakeflow.io",
        "https://agoric-rest.0base.dev",
        "https://agoric.mellifera.network:1317",
        "https://agoric-api.w3coins.io",
        "https://api.agoric.stakewith.us",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      gravitybridge: {
        portId: "transfer",
        channelId:
          "channel-4",
        counterpartyChainId:
          "gravitybridge",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-91",
        order: "unordered",
        version: "ics20-1",
      },
      stride: {
        portId: "transfer",
        channelId:
          "channel-59",
        counterpartyChainId:
          "stride",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-148",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-2",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-11",
        order: "unordered",
        version: "ics20-1",
      },
      axelar: {
        portId: "transfer",
        channelId:
          "channel-9",
        counterpartyChainId:
          "axelar",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-41",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-405",
        order: "unordered",
        version: "ics20-1",
      },
      composable: {
        portId: "transfer",
        channelId:
          "channel-55",
        counterpartyChainId:
          "composable",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-13",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-320",
        order: "unordered",
        version: "ics20-1",
      },
      kujira: {
        portId: "transfer",
        channelId:
          "channel-13",
        counterpartyChainId:
          "kujira",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-61",
        order: "unordered",
        version: "ics20-1",
      },
      archway: {
        portId: "transfer",
        channelId:
          "channel-60",
        counterpartyChainId:
          "archway",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-20",
        order: "unordered",
        version: "ics20-1",
      },
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-10",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-51",
        order: "unordered",
        version: "ics20-1",
      },
      evmos: {
        portId: "transfer",
        channelId:
          "channel-57",
        counterpartyChainId:
          "evmos",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-85",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
