/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "aioz",
  displayName: "AIOZ Network",
  website:
    "https://aioz.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/aioz/images/aioz.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/aioz/images/aioz.svg",
  },
  repository:
    "https://github.com/AIOZNetwork/go-aioz",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/aioz",
        "https://rpc-dataseed.aioz.network:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/aioz",
        "https://lcd-dataseed.aioz.network",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://eth-dataseed.aioz.network",
      ],
    },
  },
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-779",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-567",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
