/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "akash",
  displayName: "Akash",
  website:
    "https://akash.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/images/akt.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/images/akt.svg",
  },
  repository:
    "https://github.com/akash-network/node/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/akash",
        "https://rpc.akash.forbole.com:443",
        "https://rpc-akash.ecostake.com:443",
        "https://akash-rpc.lavenderfive.com:443",
        "https://akash-rpc.polkachu.com",
        "https://rpc-akash.cosmos-spaces.cloud",
        "https://rpc-akash-ia.cosmosia.notional.ventures:443",
        "http://akash.c29r3.xyz:80/rpc",
        "https://akash-mainnet-rpc.autostake.com:443",
        "https://akash.rpc.interchain.ivaldilabs.xyz",
        "https://akash-rpc.kleomedes.network",
        "https://rpc-akash-01.stakeflow.io",
        "https://akash-mainnet-rpc.cosmonautstakes.com:443",
        "https://akash-rpc.w3coins.io",
        "https://akash-rpc.publicnode.com",
        "https://akash-rpc.validatornode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/akash",
        "https://api.akash.forbole.com:443",
        "https://rest-akash.ecostake.com",
        "https://akash-api.lavenderfive.com:443",
        "https://akash-api.polkachu.com",
        "https://api-akash.cosmos-spaces.cloud",
        "https://api-akash-ia.cosmosia.notional.ventures",
        "https://akash.c29r3.xyz:443/api",
        "https://akash-mainnet-lcd.autostake.com:443",
        "https://akash.rest.interchain.ivaldilabs.xyz",
        "https://akash-api.kleomedes.network",
        "https://api-akash-01.stakeflow.io",
        "https://akash-mainnet-rest.cosmonautstakes.com:443",
        "https://akash-api.w3coins.io",
        "https://akash-rest.publicnode.com",
        "https://akash-api.validatornode.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-43",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-21",
        order: "unordered",
        version: "ics20-1",
      },
      cryptoorgchain: {
        portId: "transfer",
        channelId:
          "channel-14",
        counterpartyChainId:
          "cryptoorgchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-21",
        order: "unordered",
        version: "ics20-1",
      },
      starname: {
        portId: "transfer",
        channelId:
          "channel-23",
        counterpartyChainId:
          "starname",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-6",
        order: "unordered",
        version: "ics20-1",
      },
      persistence: {
        portId: "transfer",
        channelId:
          "channel-6",
        counterpartyChainId:
          "persistence",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-5",
        order: "unordered",
        version: "ics20-1",
      },
      regen: {
        portId: "transfer",
        channelId:
          "channel-13",
        counterpartyChainId:
          "regen",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-7",
        order: "unordered",
        version: "ics20-1",
      },
      archway: {
        portId: "transfer",
        channelId:
          "channel-109",
        counterpartyChainId:
          "archway",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-26",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-9",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-1",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-70",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-44",
        order: "unordered",
        version: "ics20-1",
      },
      irisnet: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "irisnet",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-9",
        order: "unordered",
        version: "ics20-1",
      },
      juno: {
        portId: "transfer",
        channelId:
          "channel-35",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-29",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-17",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-184",
        order: "unordered",
        version: "ics20-1",
      },
      sifchain: {
        portId: "transfer",
        channelId:
          "channel-24",
        counterpartyChainId:
          "sifchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-2",
        order: "unordered",
        version: "ics20-1",
      },
      sentinel: {
        portId: "transfer",
        channelId:
          "channel-12",
        counterpartyChainId:
          "sentinel",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-6",
        order: "unordered",
        version: "ics20-1",
      },
      kujira: {
        portId: "transfer",
        channelId:
          "channel-63",
        counterpartyChainId:
          "kujira",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-64",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
