/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "bandchain",
  displayName:
    "Band Protocol",
  website:
    "https://bandprotocol.com/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/bandchain/images/band.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/bandchain/images/band.svg",
  },
  repository:
    "https://github.com/bandprotocol/chain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/bandchain",
        "http://rpc.laozi1.bandchain.org:80",
        "https://rpc-bandchain-ia.cosmosia.notional.ventures/",
        "https://band-rpc.ibs.team/",
        "https://bandchain-mainnet-rpc.autostake.com:443",
        "https://rpc-band-01.stakeflow.io",
        "https://rpc-band.cosmos-spaces.cloud",
        "https://band-rpc.w3coins.io",
        "https://bandprotocol-rpc.highstakes.ch:26657/",
        "https://rpc.band.indonode.net",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/bandchain",
        "https://laozi1.bandchain.org/api",
        "https://api-bandchain-ia.cosmosia.notional.ventures/",
        "https://band-api.ibs.team/",
        "https://api-band.cosmos-spaces.cloud",
        "https://bandchain-mainnet-lcd.autostake.com:443",
        "https://api-band-01.stakeflow.io",
        "https://band-api.w3coins.io",
        "https://bandprotocol-api.highstakes.ch:1317/",
        "https://api.band.indonode.net",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      comdex: {
        portId: "oracle",
        channelId:
          "channel-96",
        counterpartyChainId:
          "comdex",
        counterpartyPortId:
          "bandoracleV1",
        counterpartyChannelId:
          "channel-43",
        order: "unordered",
        version:
          "bandchain-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-83",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-148",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
