/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "beezee",
  displayName: "BeeZee",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/beezee/images/bze.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/beezee/images/bze.svg",
  },
  repository:
    "https://github.com/bze-alphateam/bze",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/beezee",
        "https://rpc.getbze.com",
        "https://rpc-1.getbze.com",
        "https://rpc-2.getbze.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/beezee",
        "https://rest.getbze.com",
        "https://rest-1.getbze.com",
        "https://rest-2.getbze.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-340",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
