/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "bostrom",
  displayName: "bostrom",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/bostrom/images/boot.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/bostrom/images/boot.svg",
  },
  repository:
    "https://github.com/cybercongress/go-cyber",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/bostrom",
        "https://rpc.bostrom.cybernode.ai",
        "https://rpc.cyber.posthuman.digital",
        "https://rpc-cyber-ia.cosmosia.notional.ventures/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/bostrom",
        "https://lcd.bostrom.cybernode.ai",
        "https://lcd.cyber.posthuman.digital",
        "https://api-cyber-ia.cosmosia.notional.ventures/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-2",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-95",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
