/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "canto",
  displayName: "Canto",
  website:
    "https://canto.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/canto/images/canto.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/canto/images/canto.svg",
  },
  repository:
    "https://github.com/Canto-Network/Canto",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/canto",
        "https://rpc.canto.nodestake.top",
        "https://canto-rpc.polkachu.com",
        "https://rpc.canto.silentvalidator.com/",
        "https://canto.gravitychain.io:26657",
        "https://canto-rpc.lgns.net:443",
        "https://rpc-canto.cosmos-spaces.cloud",
        "https://rpc-canto.carbonZERO.zone:443",
        "https://canto-mainnet-rpc.autostake.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/canto",
        "https://api.canto.nodestake.top",
        "https://canto-api.polkachu.com",
        "https://api.canto.silentvalidator.com/",
        "https://canto-rest.lgns.net:443",
        "https://api-canto.cosmos-spaces.cloud",
        "https://rest-canto.carbonZERO.zone:443",
        "https://canto-mainnet-lcd.autostake.com:443",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://canto.neobase.one/",
        "https://canto.evm.chandrastation.com",
        "https://canto.slingshot.finance",
        "https://jsonrpc.canto.nodestake.top",
        "https://evm-rpc.canto.silentvalidator.com/",
        "https://canto.gravitychain.io:8545",
      ],
    },
  },
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-550",
        order: "unordered",
        version: "ics20-1",
      },
      carbon: {
        portId: "transfer",
        channelId:
          "channel-6",
        counterpartyChainId:
          "carbon",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-18",
        order: "unordered",
        version: "ics20-1",
      },
      composable: {
        portId: "transfer",
        channelId:
          "channel-23",
        counterpartyChainId:
          "composable",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-12",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
