/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "cerberus",
  displayName: "Cerberus",
  website:
    "https://cerberus.zone/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cerberus/images/crbrus.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cerberus/images/crbrus.svg",
  },
  repository:
    "https://github.com/cerberus-zone/cerberus",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/cerberus",
        "https://cerberus-rpc.polkachu.com",
        "https://cerberus-rpc.kleomedes.network",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/cerberus",
        "https://cerberus-api.polkachu.com",
        "https://cerberus-api.kleomedes.network",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-212",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
