/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "chimba",
  displayName: "Chimba",
  website:
    "https://chimba.ooo/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/chimba/images/chimba-blue.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/chimba/images/chimba-blue.svg",
  },
  repository:
    "https://github.com/ChimbaBlockchain/chimba",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/chimba",
        "https://rpc.mainnet.chimbablockchain.io",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/chimba",
        "https://mainnet.chimbablockchain.io",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
