/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "chronicnetwork",
  displayName:
    "Chronic Chain",
  website: null,
  logo: {
    png: null,
    svg: null,
  },
  repository:
    "https://github.com/ChronicNetwork/cht",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/chronicnetwork",
        "https://rpc-chronic.zenchainlabs.io/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/chronicnetwork",
        "https://api-chronic.zenchainlabs.io/",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
