/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "cronos",
  displayName: "Cronos",
  website:
    "https://cronos.org",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cronos/images/cronos.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cronos/images/cro.svg",
  },
  repository:
    "https://github.com/crypto-org-chain/cronos",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/cronos",
        "https://rpc.cronos.org/",
        "https://rpc-cronos.cosmos-spaces.cloud",
        "https://cronos-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/cronos",
        "https://rest.cronos.org/",
        "https://api-cronos.cosmos-spaces.cloud",
        "https://cronos-rest.publicnode.com",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://evm.cronos.org/",
        "https://cronos-evm.publicnode.com",
      ],
    },
  },
  ibc: {
    channels: {
      kava: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "kava",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-125",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
