/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "cudos",
  displayName: "Cudos",
  website:
    "https://www.cudos.org/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cudos/images/cudos.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/cudos/images/cudos.svg",
  },
  repository:
    "https://github.com/CudoVentures/cudos-node",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/cudos",
        "http://mainnet-full-node-01.hosts.cudos.org:26657",
        "https://mainnet-full-node-02.hosts.cudos.org:36657",
        "https://cudos-rpc.kleomedes.network",
        "https://cudos-mainnet-rpc.autostake.com:443",
        "https://cudos-rpc.lavenderfive.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/cudos",
        "http://mainnet-full-node-01.hosts.cudos.org:1317",
        "https://mainnet-full-node-02.hosts.cudos.org:31317",
        "https://cudos-api.kleomedes.network",
        "https://cudos-mainnet-lcd.autostake.com:443",
        "https://cudos-api.lavenderfive.com/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-298",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
