/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "desmos",
  displayName: "Desmos",
  website:
    "https://desmos.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/desmos/images/dsm.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/desmos/images/dsm.svg",
  },
  repository:
    "https://github.com/desmos-labs/desmos",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/desmos",
        "https://rpc.mainnet.desmos.network",
        "https://desmos-rpc.lavenderfive.com/",
        "https://desmos-rpc.ibs.team/",
        "https://desmos.nodejumper.io",
        "https://rpc-desmos.whispernode.com:443",
        "https://rpc-desmos.explorer.co.id",
        "https://desmos-rpc.staketab.org:443",
        "https://desmos-rpc.panthea.eu",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/desmos",
        "https://api.mainnet.desmos.network",
        "https://desmos-api.lavenderfive.com/",
        "https://desmos-api.ibs.team/",
        "https://desmos.nodejumper.io:1317",
        "https://api-desmos.explorer.co.id",
        "https://desmos-rest.staketab.org",
        "https://desmos-api.panthea.eu",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-2",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-135",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
