/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "dig",
  displayName: "Dig Chain",
  website:
    "https://digchain.org/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/dig/images/dig.png",
    svg: null,
  },
  repository:
    "https://github.com/notional-labs/dig",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/dig",
        "https://rpc-1-dig.notional.ventures",
        "https://rpc-dig-ia.cosmosia.notional.ventures/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/dig",
        "https://api-1-dig.notional.ventures",
        "https://api-dig-ia.cosmosia.notional.ventures/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      juno: {
        portId: "transfer",
        channelId:
          "channel-2",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-37",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-128",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
