/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "empowerchain",
  displayName: "EmpowerChain",
  website: null,
  logo: {
    png: null,
    svg: null,
  },
  repository:
    "https://github.com/EmpowerPlastic/empowerchain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/empowerchain",
        "https://rpc-empowerchain.ecostake.com:443",
        "https://empowerchain-mainnet-rpc.autostake.com:443",
        "https://empower.rpc.liveraven.net",
        "https://rpc-empower.whispernode.com:443",
        "https://rpc-empowerchain.mzonder.com:443",
        "https://rpc.empower.indonode.net:443",
        "https://empower-rpc.w3coins.io",
        "https://rpc-empower.vinjan.xyz:443",
        "https://rpc.empower.nodestake.top",
        "https://mainnet-empower-rpc.konsortech.xyz",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/empowerchain",
        "https://rest-empowerchain.ecostake.com:443",
        "https://empowerchain-mainnet-lcd.autostake.com:443",
        "https://empower.api.liveraven.net",
        "https://empower-api.w3coins.io",
        "https://lcd-empower.whispernode.com:443",
        "https://api-empowerchain.mzonder.com:443",
        "https://api.empower.indonode.net:443",
        "https://api-empower.vinjan.xyz:443",
        "https://api.empower.nodestake.top",
        "https://mainnet-empower-api.konsortech.xyz",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-1411",
        order: "unordered",
        version: "ics20-1",
      },
      axelar: {
        portId: "transfer",
        channelId:
          "channel-2",
        counterpartyChainId:
          "axelar",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-109",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-621",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
