/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "ethos",
  displayName: "Ethos",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/ethos/images/ethos.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/ethos/images/ethos.svg",
  },
  repository: null,
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/ethos",
        "https://ethos-rpc.provable.dev:443/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/ethos",
        "https://ethos.provable.dev/rest/",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://ethos-evm.provable.dev/",
      ],
    },
  },
  ibc: {},
} as const;
