/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "fetchhub",
  displayName: "Fetch.ai",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/fetchhub/images/fet.svg",
  },
  repository:
    "https://github.com/fetchai/fetchd",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/fetchhub",
        "https://rpc-fetchhub.fetch.ai:443",
        "https://rpc-fetchhub-ia.cosmosia.notional.ventures/",
        "https://fetch-rpc.polkachu.com",
        "https://fetchai-rpc.kleomedes.network",
        "https://fetch-rpc.teasel.org",
        "https://fetch-rpc.antrixy.org",
        "https://rpc-fetch.architectnodes.com",
        "https://fetchhub-mainnet-rpc.autostake.com:443",
        "https://fetch-rpc.ibs.team",
        "https://fetch-rpc.cosmosrescue.com",
        "https://fetch-rpc.w3coins.io",
        "https://fetch-rpc.publicnode.com",
        "https://fetch-rpc.highstakes.ch:26657/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/fetchhub",
        "https://rest-fetchhub.fetch.ai",
        "https://api-fetchhub-ia.cosmosia.notional.ventures/",
        "https://fetch-api.polkachu.com",
        "https://fetchai-api.kleomedes.network",
        "https://fetch-rest.teasel.org",
        "https://fetch-rest.antrixy.org",
        "https://fetchhub-mainnet-lcd.autostake.com:443",
        "https://rest-fetch.architectnodes.com",
        "https://fetch-api.ibs.team",
        "https://fetch-api.cosmosrescue.com",
        "https://fetch-api.w3coins.io",
        "https://fetch-rest.publicnode.com",
        "https://fetch-api.highstakes.ch:1317/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-10",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-229",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
