/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "firmachain",
  displayName: "FirmaChain",
  website:
    "https://firmachain.org/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/firmachain/images/fct.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/firmachain/images/fct.svg",
  },
  repository:
    "https://github.com/firmachain/firmachain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/firmachain",
        "https://lcd-mainnet.firmachain.dev:26657",
        "https://rpc.firmachain.chaintools.tech/",
        "https://firmachain-rpc.lavenderfive.com/",
        "https://firmachain-rpc.ramuchi.tech",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/firmachain",
        "https://lcd-mainnet.firmachain.dev:1317",
        "https://api.firmachain.chaintools.tech/",
        "https://firmachain-api.lavenderfive.com/",
        "https://firmachain-api.ramuchi.tech",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
