/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "galaxy",
  displayName: "Galaxy",
  website:
    "https://galaxychain.zone/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/galaxy/images/glx.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/galaxy/images/glx.svg",
  },
  repository:
    "https://github.com/galaxies-labs/galaxy",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/galaxy",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/galaxy",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-236",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
