/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "gateway",
  displayName:
    "Wormhole Gateway",
  website:
    "https://wormhole.com",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/gateway/images/gateway_logo.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/gateway/images/wormhole_logo.svg",
  },
  repository:
    "https://github.com/wormhole-foundation/wormhole",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/gateway",
        "https://wormchain-rpc.quickapi.com/",
        "https://wormchain.jumpisolated.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/gateway",
        "https://wormchain-lcd.quickapi.com/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-3",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-2186",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
