/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "genesisl1",
  displayName: "GenesisL1",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/genesisl1/images/l1.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/genesisl1/images/l1.svg",
  },
  repository:
    "https://github.com/alpha-omega-labs/genesisd",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/genesisl1",
        "https://26657.genesisl1.org",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/genesisl1",
        "https://api.genesisl1.org",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-253",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
