/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "haqq",
  displayName: "Haqq Network",
  website:
    "https://haqq.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/haqq/images/haqq.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/haqq/images/haqq.svg",
  },
  repository:
    "https://github.com/haqq-network/haqq",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/haqq",
        "https://rpc.tm.haqq.network",
        "https://m-s1-tm.haqq.sh",
        "https://rpc.haqq.nodestake.top",
        "https://haqq-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/haqq",
        "https://rest.cosmos.haqq.network",
        "https://m-s1-sdk.haqq.sh",
        "https://api.haqq.nodestake.top",
        "https://haqq-rest.publicnode.com",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://rpc.eth.haqq.network",
        "https://m-s1-evm-rpc.haqq.sh",
        "https://jsonrpc.haqq.nodestake.top",
        "https://haqq-evm.publicnode.com",
      ],
    },
  },
  ibc: {},
} as const;
