/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "highbury",
  displayName: "Highbury",
  website:
    "https://www.fury.black/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/highbury/images/fury.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/highbury/images/fury.svg",
  },
  repository:
    "https://github.com/Four4Two/fury/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/highbury",
        "https://gridiron.furya.io",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/highbury",
        "https://api-mainnet.furya.io/",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://rest.furya.io/",
      ],
    },
  },
  ibc: {},
} as const;
