/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "idep",
  displayName: "IDEP",
  website:
    "https://www.idep.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/idep/images/idep.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/idep/images/idep.svg",
  },
  repository:
    "https://github.com/IDEP-network/ion",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/idep",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/idep",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
