/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "impacthub",
  displayName: "ixo",
  website:
    "https://www.ixo.world/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.svg",
  },
  repository:
    "https://github.com/ixofoundation/ixo-blockchain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/impacthub",
        "https://proxies.sifchain.finance/api/impacthub-3/rpc",
        "https://impacthub.ixo.world/rpc/",
        "https://rpc-ixo-ia.cosmosia.notional.ventures/",
        "https://impacthub-rpc.lavenderfive.com/",
        "https://ixo-rpc.ibs.team",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/impacthub",
        "https://proxies.sifchain.finance/api/impacthub-3/rest",
        "https://impacthub.ixo.world/rest/",
        "https://api-ixo-ia.cosmosia.notional.ventures/",
        "https://impacthub-api.lavenderfive.com/",
        "https://ixo-api.ibs.team",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-4",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-38",
        order: "unordered",
        version: "ics20-1",
      },
      axelar: {
        portId: "transfer",
        channelId:
          "channel-23",
        counterpartyChainId:
          "axelar",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-114",
        order: "unordered",
        version: "ics20-1",
      },
      sifchain: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "sifchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-15",
        order: "unordered",
        version: "ics20-1",
      },
      noble: {
        portId: "transfer",
        channelId:
          "channel-26",
        counterpartyChainId:
          "noble",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-15",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-204",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
