/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "kava",
  displayName: "Kava",
  website:
    "https://www.kava.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.svg",
  },
  repository:
    "https://github.com/kava-Labs/kava/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/kava",
        "https://rpc.data.kava.io",
        "https://kava-rpc.polkachu.com",
        "https://rpc-kava-ia.cosmosia.notional.ventures/",
        "https://kava-mainnet-rpc.autostake.com:443",
        "https://kava-rpc.ibs.team",
        "https://rpc-kava-01.stakeflow.io",
        "https://kava-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/kava",
        "https://api.data.kava.io/",
        "https://api-kava-ia.cosmosia.notional.ventures/",
        "https://kava-api.polkachu.com",
        "https://kava-mainnet-lcd.autostake.com:443",
        "https://kava-api.ibs.team",
        "https://api-kava-01.stakeflow.io",
        "https://kava-rest.publicnode.com",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [
        "https://evm.kava.io/",
        "https://kava-evm.publicnode.com",
        "https://kava.api.onfinality.io/public",
      ],
    },
  },
  ibc: {
    channels: {
      kujira: {
        portId: "transfer",
        channelId:
          "channel-116",
        counterpartyChainId:
          "kujira",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-95",
        order: "unordered",
        version: "ics20-1",
      },
      sei: {
        portId: "transfer",
        channelId:
          "channel-132",
        counterpartyChainId:
          "sei",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-18",
        order: "unordered",
        version: "ics20-1",
      },
      evmos: {
        portId: "transfer",
        channelId:
          "channel-117",
        counterpartyChainId:
          "evmos",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-83",
        order: "unordered",
        version: "ics20-1",
      },
      injective: {
        portId: "transfer",
        channelId:
          "channel-122",
        counterpartyChainId:
          "injective",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-143",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-277",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-143",
        order: "unordered",
        version: "ics20-1",
      },
      cronos: {
        portId: "transfer",
        channelId:
          "channel-125",
        counterpartyChainId:
          "cronos",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-11",
        order: "unordered",
        version: "ics20-1",
      },
      aura: {
        portId: "transfer",
        channelId:
          "channel-124",
        counterpartyChainId:
          "aura",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-7",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
