/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "mayachain",
  displayName:
    "Maya Protocol",
  website:
    "https://mayaprotocol.com/",
  logo: {
    png: null,
    svg: null,
  },
  repository:
    "https://gitlab.com/mayachain/mayanode",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/mayachain",
        "https://tendermint.mayachain.info",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/mayachain",
        "https://mayanode.mayachain.info",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
