/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "medasdigital",
  displayName:
    "Medas Digital Network",
  website:
    "https://medas-digital.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/medasdigital/images/medas.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/medasdigital/images/medas.svg",
  },
  repository:
    "https://github.com/oxygene76/medasdigital/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/medasdigital",
        "https://rpc.medas-digital.io:26657/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/medasdigital",
        "https://lcd.medas-digital.io:1317/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-519",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
