/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "microtick",
  displayName: "Microtick",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/microtick/images/tick.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/microtick/images/tick.svg",
  },
  repository:
    "https://github.com/microtick/mtzone",
  tendermint: null,
  cosmossdk: null,
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-16",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-39",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
