/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "mises",
  displayName: "Mises",
  website:
    "https://mises.site",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/mises/images/mises.png",
    svg: null,
  },
  repository:
    "https://github.com/mises-id/mises-tm",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/mises",
        "https://rpc.gw.mises.site:443",
        "https://e1.mises.site:443",
        "https://e2.mises.site:443",
        "https://w1.mises.site:443",
        "https://w2.mises.site:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/mises",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
