/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "mun",
  displayName: "Mun",
  website:
    "https://mun.money",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/mun/images/mun.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/mun/images/mun.svg",
  },
  repository:
    "https://github.com/munblockchain/mun-node",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/mun",
        "https://mainnet1rpc.mun.money",
        "https://rpc.mun.indonode.net",
        "https://mainnet-mun-rpc.konsortech.xyz",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/mun",
        "https://mainnet1.mun.money",
        "https://api.mun.indonode.net",
        "https://mainnet-mun-api.konsortech.xyz",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
