/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "mythos",
  displayName: "Mythos",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/mythos/images/mythos.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/mythos/images/mythos.svg",
  },
  repository: null,
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/mythos",
        "https://mythos-rpc.provable.dev:443/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/mythos",
        "https://mythos.provable.dev/rest/",
      ],
    },
  },
  evm: {
    api: {
      "jsonrpc-http": [],
    },
  },
  ibc: {},
} as const;
