/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "nomic",
  displayName: "Nomic",
  website:
    "https://nomic.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/images/nomic.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/images/nomic.svg",
  },
  repository:
    "https://github.com/nomic-io/nomic",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/nomic",
        "http://138.197.71.46:26657",
        "https://nomic-rpc.polkachu.com/",
        "https://rpc.nomic.interbloc.org",
        "https://rpc.nomic.bh.rocks",
        "https://rpc-nomic.whispernode.com:443",
        "https://rpc-nomic.carbonZERO.zone:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/nomic",
        "https://app.nomic.io:8443",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
