/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "nyx",
  displayName: "Nym",
  website:
    "https://nymtech.net/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/nyx/images/nyx.png",
    svg: null,
  },
  repository:
    "https://github.com/nymtech/nyxd/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/nyx",
        "https://rpc.nyx.nodes.guru/",
        "https://nym.vladiatorlabs.io/",
        "https://rpc.nym.forbole.com/",
        "https://rpc-nyx.testnet.run/",
        "https://nym-mainnet-rpc.commodum.io/",
        "https://nym-rpc.polkachu.com/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/nyx",
        "https://nym-api.polkachu.com/",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
