/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "octa",
  displayName: "Octa",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/octa/images/octa.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/octa/images/octa.svg",
  },
  repository: "",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/octa",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/octa",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
