/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "okexchain",
  displayName: "OKExChain",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/okexchain/images/okc.png",
    svg: null,
  },
  repository:
    "https://github.com/okex/exchain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/okexchain",
        "https://exchaintmrpc.okex.org",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/okexchain",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      assetmantle: {
        portId: "transfer",
        channelId:
          "channel-30",
        counterpartyChainId:
          "assetmantle",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-14",
        order: "unordered",
        version: "ics20-1",
      },
      vidulum: {
        portId: "transfer",
        channelId:
          "channel-37",
        counterpartyChainId:
          "vidulum",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-11",
        order: "unordered",
        version: "ics20-1",
      },
      juno: {
        portId: "transfer",
        channelId:
          "channel-52",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-212",
        order: "unordered",
        version: "ics20-1",
      },
      chihuahua: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "chihuahua",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-24",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-46",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-31",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
