/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "onomy",
  displayName: "Onomy",
  website:
    "https://onomy.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/onomy/images/nom.png",
    svg: null,
  },
  repository:
    "https://github.com/onomyprotocol/onomy",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/onomy",
        "https://rpc-mainnet.onomy.io",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/onomy",
        "https://rest-mainnet.onomy.io",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-525",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
