/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "panacea",
  displayName: "Medibloc",
  website:
    "https://medibloc.com/en/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/panacea/images/med.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/panacea/images/med.svg",
  },
  repository:
    "https://github.com/medibloc/panacea-core",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/panacea",
        "https://rpc.gopanacea.org",
        "https://panacea-rpc.staketab.org:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/panacea",
        "https://api.gopanacea.org",
        "https://panacea-rest.staketab.org",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-82",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
