/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "passage1",
  displayName: "Passage",
  website:
    "https://passage3d.com/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/passage/images/pasg.png",
    svg: null,
  },
  repository:
    "https://github.com/envadiv/Passage3D",
  tendermint: null,
  cosmossdk: null,
  evm: null,
  ibc: {},
} as const;
