/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "persistence",
  displayName: "Persistence",
  website:
    "https://persistence.one/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.svg",
  },
  repository:
    "https://github.com/persistenceOne/persistenceCore",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/persistence",
        "https://rpc.core.persistence.one",
        "https://rpc-persistent-ia.cosmosia.notional.ventures/",
        "https://persistence-rpc.polkachu.com",
        "https://persistence-rpc.kleomedes.network",
        "https://rpc-persistence.architectnodes.com",
        "https://rpc-persistence.cosmos-spaces.cloud",
        "https://persistence-mainnet-rpc.cosmonautstakes.com",
        "https://persistence-rpc.quantnode.tech",
        "https://persistence-rpc.zenscape.one",
        "https://persistence-mainnet-rpc.autostake.com:443",
        "https://persistence-rpc.stakeandrelax.net",
        "https://rpc.persistence.posthuman.digital:443",
        "http://141.95.33.97:21657/websocket",
        "https://rpc-persistence-01.stakeflow.io",
        "https://persistence-rpc.w3coins.io",
        "https://persistence-rpc.publicnode.com",
        "https://persistence-rpc.highstakes.ch:26657/",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/persistence",
        "https://rest.core.persistence.one",
        "https://api-persistent-ia.cosmosia.notional.ventures/",
        "https://api-persistence.starsquid.io",
        "https://persistence-api.polkachu.com",
        "https://api-persistence.cosmos-spaces.cloud",
        "https://persistence-api.kleomedes.network",
        "https://rest-persistence.architectnodes.com",
        "https://persistence-mainnet-lcd.autostake.com:443",
        "https://persistence-mainnet-rest.cosmonautstakes.com",
        "https://persistence-lcd.quantnode.tech",
        "https://persistence-rest.zenscape.one",
        "https://persistence-api.stakeandrelax.net",
        "https://rest.persistence.posthuman.digital:443",
        "http://141.95.33.97:1317",
        "https://api-persistence-01.stakeflow.io",
        "https://persistence-api.w3coins.io",
        "https://persistence-rest.publicnode.com",
        "https://persistence-api.highstakes.ch:1317/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      irisnet: {
        portId: "transfer",
        channelId:
          "channel-19",
        counterpartyChainId:
          "irisnet",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-15",
        order: "unordered",
        version: "ics20-1",
      },
      starname: {
        portId: "transfer",
        channelId:
          "channel-27",
        counterpartyChainId:
          "starname",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-13",
        order: "unordered",
        version: "ics20-1",
      },
      akash: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "akash",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-6",
        order: "unordered",
        version: "ics20-1",
      },
      quicksilver: {
        portId: "transfer",
        channelId:
          "channel-73",
        counterpartyChainId:
          "quicksilver",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-16",
        order: "unordered",
        version: "ics20-1",
      },
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-82",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-64",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-6",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-4",
        order: "unordered",
        version: "ics20-1",
      },
      comdex: {
        portId: "transfer",
        channelId:
          "channel-71",
        counterpartyChainId:
          "comdex",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-57",
        order: "unordered",
        version: "ics20-1",
      },
      regen: {
        portId: "transfer",
        channelId:
          "channel-21",
        counterpartyChainId:
          "regen",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-14",
        order: "unordered",
        version: "ics20-1",
      },
      injective: {
        portId: "transfer",
        channelId:
          "channel-41",
        counterpartyChainId:
          "injective",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-82",
        order: "unordered",
        version: "ics20-1",
      },
      cryptoorgchain: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "cryptoorgchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-17",
        order: "unordered",
        version: "ics20-1",
      },
      umee: {
        portId: "transfer",
        channelId:
          "channel-81",
        counterpartyChainId:
          "umee",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-51",
        order: "unordered",
        version: "ics20-1",
      },
      sifchain: {
        portId: "transfer",
        channelId:
          "channel-26",
        counterpartyChainId:
          "sifchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-7",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-68",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-30",
        order: "unordered",
        version: "ics20-1",
      },
      juno: {
        portId: "transfer",
        channelId:
          "channel-37",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-33",
        order: "unordered",
        version: "ics20-1",
      },
      sentinel: {
        portId: "transfer",
        channelId:
          "channel-22",
        counterpartyChainId:
          "sentinel",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-15",
        order: "unordered",
        version: "ics20-1",
      },
      gravitybridge: {
        portId: "transfer",
        channelId:
          "channel-38",
        counterpartyChainId:
          "gravitybridge",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-24",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-24",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-190",
        order: "unordered",
        version: "ics20-1",
      },
      stride: {
        portId: "transfer",
        channelId:
          "channel-67",
        counterpartyChainId:
          "stride",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-53",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
