/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "quasar",
  displayName: "Quasar",
  website:
    "https://www.quasar.fi/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/quasar/images/quasar.png",
    svg: null,
  },
  repository:
    "https://github.com/quasar-finance/quasar-preview",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/quasar",
        "https://quasar-rpc.lavenderfive.com:443",
        "https://quasar-rpc.polkachu.com",
        "https://rpc-quasar.whispernode.com:443",
        "https://quasar-rpc.enigma-validator.com",
        "https://rpc-quasar.cosmos-spaces.cloud",
        "https://quasar-mainnet-rpc.autostake.com:443",
        "https://quasar.rpc.kjnodes.com",
        "https://rpc-quasar.validavia.me",
        "https://quasar-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/quasar",
        "https://quasar-api.lavenderfive.com:443",
        "https://quasar-api.polkachu.com",
        "https://lcd-quasar.whispernode.com:443",
        "https://api-quasar.cosmos-spaces.cloud",
        "https://quasar-lcd.enigma-validator.com",
        "https://quasar-mainnet-lcd.autostake.com:443",
        "https://quasar.api.kjnodes.com",
        "https://lcd-quasar.validavia.me",
        "https://quasar-rest.publicnode.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-688",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
