/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "qwoyn",
  displayName: "Qwoyn",
  website:
    "https://qwoyn.studio/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/qwoyn/images/qwoyn.png",
    svg: null,
  },
  repository:
    "https://github.com/cosmic-horizon/QWOYN",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/qwoyn",
        "https://rpc.qwoyn.studio:443",
        "https://rpc-qwoyn.theamsolutions.info:443",
        "https://qwoyn-rpc.staketab.org:443",
        "https://qwoyn-rpc-archive.staketab.org:443",
        "https://qwoyn-rpc.lavenderfive.com:443",
        "https://rpc-qwoyn.mzonder.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/qwoyn",
        "https://rest-qwoyn.theamsolutions.info:443",
        "https://qwoyn-rest.staketab.org",
        "https://qwoyn-rest-archive.staketab.org",
        "https://qwoyn-api.lavenderfive.com",
        "https://api-qwoyn.mzonder.com",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
