/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "rebus",
  displayName: "Rebus",
  website:
    "https://www.rebuschain.com/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/rebus/images/rebus.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/rebus/images/rebus.svg",
  },
  repository:
    "https://github.com/rebuschain/rebus.core",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/rebus",
        "https://api.rebuschain.com:26657/",
        "https://rebus.rpc.bccnodes.com:443",
        "https://rebus.rpc.manticore.team:443/",
        "https://rpc.rebus.nodestake.top/",
        "http://rebus.rpc.m.stavr.tech:40107",
        "https://rpc-1.rebus.nodes.guru",
        "https://api.mainnet.rebus.money:26657",
        "https://rpc-rebus.d-stake.xyz",
        "https://rebus-rpc.brocha.in",
        "https://rebus.nodejumper.io",
        "https://rpc.rebus.bh.rocks",
        "https://rebus-rpc.kleomedes.network",
        "https://rpc-rebus.huginn.tech",
        "https://rebus-mainnet-rpc.autostake.com:443",
        "https://rebus.rpc.liveraven.net",
        "https://rpc.rebus.safeblock.space",
        "https://rebus-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/rebus",
        "https://api.rebuschain.com:1317/",
        "https://rebus.api.bccnodes.com:443",
        "https://rebus.api.manticore.team:443/",
        "https://api.rebus.nodestake.top/",
        "https://rebus.api.m.stavr.tech",
        "https://api-1.rebus.nodes.guru",
        "https://api.mainnet.rebus.money:1317",
        "https://api-rebus.d-stake.xyz",
        "https://rebus-rest.brocha.in",
        "https://rebus.nodejumper.io:1317",
        "https://rebus-api.kleomedes.network",
        "https://rebus-mainnet-lcd.autostake.com:443",
        "https://rebus.api.liveraven.net",
        "https://api.rebus.safeblock.space",
        "https://rebus-rest.publicnode.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-355",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
