/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "sei",
  displayName: "Sei",
  website:
    "https://www.sei.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.svg",
  },
  repository:
    "https://github.com/sei-protocol/sei-chain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/sei",
        "https://sei-rpc.lavenderfive.com:443",
        "https://sei-rpc.polkachu.com/",
        "https://sei-rpc.brocha.in/",
        "https://sei-mainnet-rpc.autostake.com:443",
        "https://rpc-sei.stingray.plus/",
        "https://rpc-sei.rhinostake.com",
        "https://rpc-sei.whispernode.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/sei",
        "https://sei-api.lavenderfive.com:443",
        "https://sei-api.polkachu.com/",
        "https://sei-rest.brocha.in/",
        "https://api-sei.stingray.plus/",
        "https://sei-mainnet-lcd.autostake.com:443",
        "https://rest-sei.rhinostake.com",
        "https://lcd-sei.whispernode.com:443",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      neutron: {
        portId: "transfer",
        channelId:
          "channel-15",
        counterpartyChainId:
          "neutron",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-19",
        order: "unordered",
        version: "ics20-1",
      },
      stride: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "stride",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-149",
        order: "unordered",
        version: "ics20-1",
      },
      kava: {
        portId: "transfer",
        channelId:
          "channel-18",
        counterpartyChainId:
          "kava",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-132",
        order: "unordered",
        version: "ics20-1",
      },
      planq: {
        portId: "transfer",
        channelId:
          "channel-13",
        counterpartyChainId:
          "planq",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-59",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-782",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
