/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "sge",
  displayName: "SGE",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/sge/images/sge.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/sge/images/sge.svg",
  },
  repository:
    "https://github.com/sge-network/sge",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/sge",
        "https://sge-rpc.lavenderfive.com/",
        "https://sge-rpc.polkachu.com/",
        "https://rpc.sge.nodestake.top/",
        "https://rpc-sge.nodeist.net/",
        "https://sge-rpc.ramuchi.tech",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/sge",
        "https://sge-api.lavenderfive.com/",
        "https://sge-api.polkachu.com/",
        "https://api.sge.nodestake.top/",
        "https://api-sge.nodeist.net/",
        "https://sge-api.ramuchi.tech/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-5485",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
