/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "shareledger",
  displayName: "Shareledger",
  website:
    "https://www.sharering.network/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/shareledger/images/chain-logo.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/shareledger/images/token.svg",
  },
  repository:
    "https://github.com/ShareRing/Shareledger/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/shareledger",
        "https://rpc.explorer.shareri.ng",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/shareledger",
        "https://lcd.explorer.shareri.ng/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-647",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
