/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "stride",
  displayName: "Stride",
  website:
    "https://stride.zone/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/stride-chain-logo.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.svg",
  },
  repository:
    "https://github.com/Stride-Labs/stride",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/stride",
        "https://stride.rpc.bccnodes.com:443",
        "https://stride-rpc.polkachu.com/",
        "https://stride-rpc.onivalidator.com",
        "https://stride.rpc.chandrastation.com",
        "http://rpc-stride.nodeist.net",
        "https://stride-rpc.lavenderfive.com/",
        "https://rpc.stride.silentvalidator.com/",
        "https://rpc-stride.cosmos-spaces.cloud",
        "http://stride.rpc.m.stavr.tech:21017",
        "https://stride.rpc.kjnodes.com",
        "https://rpc-stride.pupmos.network",
        "https://rpc-stride.architectnodes.com",
        "https://stride.nodejumper.io",
        "https://rpc-stride.whispernode.com:443",
        "https://rpc-stride.carbonZERO.zone:443",
        "https://stride-mainnet-rpc.autostake.com:443",
        "https://stride-rpc.stakeandrelax.net",
        "https://stride.rpc.interchain.ivaldilabs.xyz",
        "https://rpc-stride-01.stakeflow.io",
        "https://rpc.stride.stake-take.com",
        "https://stride-rpc.w3coins.io",
        "https://stride-rpc.publicnode.com",
        "https://community.nuxian-node.ch:6797/stride/trpc",
        "https://rpc-stride.in3s.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/stride",
        "https://stride.api.bccnodes.com:443",
        "https://stride-api.polkachu.com/",
        "https://stride.api.chandrastation.com",
        "http://api-stride.nodeist.net",
        "https://api-stride.cosmos-spaces.cloud",
        "https://stride.api.m.stavr.tech",
        "https://stride-api.lavenderfive.com/",
        "https://api.stride.silentvalidator.com/",
        "https://stride.api.kjnodes.com",
        "https://api-stride.pupmos.network",
        "https://stride.nodejumper.io:1317",
        "https://stride-mainnet-lcd.autostake.com:443",
        "https://rest-stride.architectnodes.com",
        "https://lcd-stride.whispernode.com:443",
        "https://rest-stride.carbonZERO.zone:443",
        "https://stride-api.stakeandrelax.net",
        "https://stride.rest.interchain.ivaldilabs.xyz",
        "https://api-stride-01.stakeflow.io",
        "https://api.stride.stake-take.com",
        "https://stride-api.w3coins.io",
        "https://stride-rest.publicnode.com",
        "https://community.nuxian-node.ch:6797/stride/crpc",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      carbon: {
        portId: "transfer",
        channelId:
          "channel-47",
        counterpartyChainId:
          "carbon",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-8",
        order: "unordered",
        version: "ics20-1",
      },
      sei: {
        portId: "transfer",
        channelId:
          "channel-149",
        counterpartyChainId:
          "sei",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-11",
        order: "unordered",
        version: "ics20-1",
      },
      axelar: {
        portId: "transfer",
        channelId:
          "channel-69",
        counterpartyChainId:
          "axelar",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-64",
        order: "unordered",
        version: "ics20-1",
      },
      kujira: {
        portId: "transfer",
        channelId:
          "channel-8",
        counterpartyChainId:
          "kujira",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-32",
        order: "unordered",
        version: "ics20-1",
      },
      cosmoshub: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "cosmoshub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-391",
        order: "unordered",
        version: "ics20-1",
      },
      agoric: {
        portId: "transfer",
        channelId:
          "channel-148",
        counterpartyChainId:
          "agoric",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-59",
        order: "unordered",
        version: "ics20-1",
      },
      sommelier: {
        portId: "transfer",
        channelId:
          "channel-150",
        counterpartyChainId:
          "sommelier",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-71",
        order: "unordered",
        version: "ics20-1",
      },
      terra2: {
        portId: "transfer",
        channelId:
          "channel-52",
        counterpartyChainId:
          "terra2",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-46",
        order: "unordered",
        version: "ics20-1",
      },
      neutron: {
        portId: "transfer",
        channelId:
          "channel-123",
        counterpartyChainId:
          "neutron",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-8",
        order: "unordered",
        version: "ics20-1",
      },
      injective: {
        portId: "transfer",
        channelId:
          "channel-6",
        counterpartyChainId:
          "injective",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-89",
        order: "unordered",
        version: "ics20-1",
      },
      comdex: {
        portId: "transfer",
        channelId:
          "channel-49",
        counterpartyChainId:
          "comdex",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-45",
        order: "unordered",
        version: "ics20-1",
      },
      evmos: {
        portId: "transfer",
        channelId:
          "channel-9",
        counterpartyChainId:
          "evmos",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-25",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-51",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-29",
        order: "unordered",
        version: "ics20-1",
      },
      umee: {
        portId: "transfer",
        channelId:
          "channel-29",
        counterpartyChainId:
          "umee",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-34",
        order: "unordered",
        version: "ics20-1",
      },
      juno: {
        portId: "transfer",
        channelId:
          "channel-24",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-139",
        order: "unordered",
        version: "ics20-1",
      },
      acrechain: {
        portId: "transfer",
        channelId:
          "channel-57",
        counterpartyChainId:
          "acrechain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-13",
        order: "unordered",
        version: "ics20-1",
      },
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-40",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-37",
        order: "unordered",
        version: "ics20-1",
      },
      composable: {
        portId: "transfer",
        channelId:
          "channel-134",
        counterpartyChainId:
          "composable",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-5",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-5",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-326",
        order: "unordered",
        version: "ics20-1",
      },
      stargaze: {
        portId: "transfer",
        channelId:
          "channel-19",
        counterpartyChainId:
          "stargaze",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-106",
        order: "unordered",
        version: "ics20-1",
      },
      persistence: {
        portId: "transfer",
        channelId:
          "channel-53",
        counterpartyChainId:
          "persistence",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-67",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
