/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "teritori",
  displayName: "Teritori",
  website:
    "https://teritori.com/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/teritori/images/chain.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/teritori/images/chain.svg",
  },
  repository:
    "https://github.com/TERITORI/teritori-chain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/teritori",
        "https://teritori-rpc.lavenderfive.com:443",
        "https://teritori-rpc.polkachu.com",
        "https://rpc.teritori.nodestake.top",
        "https://teritori.rpc.m.stavr.tech",
        "https://rpc.teritori.silentvalidator.com/",
        "https://teritori-rpc.brocha.in",
        "https://teritori.nodejumper.io",
        "https://teritori-rpc.ibs.team",
        "https://rpc-teritori.mms.team/",
        "https://teritori.rpc.kjnodes.com",
        "https://rpc.tori.bh.rocks",
        "https://teritori-rpc.kleomedes.network",
        "https://m-teritori.rpc.utsa.tech",
        "https://teritori.rpc.silknodes.io",
        "https://rpc-teritori.pupmos.network",
        "https://rpc-teritori.whispernode.com:443",
        "https://rpc-teritori.carbonZERO.zone:443",
        "https://teritori-mainnet-rpc.autostake.com:443",
        "https://rpc-teritori.ecostake.com",
        "https://teritori-rpc.publicnode.com",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/teritori",
        "https://teritori-api.lavenderfive.com:443",
        "https://teritori-api.polkachu.com",
        "https://api.teritori.nodestake.top",
        "https://teritori.api.m.stavr.tech",
        "https://api.teritori.silentvalidator.com/",
        "https://teritori.nodejumper.io:1317",
        "https://teritori-api.ibs.team",
        "https://api-teritori.mms.team/",
        "https://teritori.api.kjnodes.com",
        "https://api.tori.bh.rocks",
        "https://teritori-api.kleomedes.network",
        "https://m-teritori.api.utsa.tech",
        "https://teritori.api.silknodes.io",
        "https://api-teritori.pupmos.network",
        "https://lcd-teritori.whispernode.com:443",
        "https://rest-teritori.carbonZERO.zone:443",
        "https://teritori-mainnet-lcd.autostake.com:443",
        "https://rest-teritori.ecostake.com",
        "https://teritori-rest.publicnode.com",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-362",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
