/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "terpnetwork",
  displayName: "Terp-Network",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/terpnetwork/images/logo.png",
    svg: null,
  },
  repository:
    "https://github.com/terpnetwork/terp-core.git",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/terpnetwork",
        "https://rpc-terp.zenchainlabs.io/",
        "https://rpc.terp.nodestake.top:443",
        "https://terp-mainnet-rpc.itrocket.net:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/terpnetwork",
        "https://api-terp.zenchainlabs.io:443",
        "https://rpc.terp.nodestake.top:443",
        "https://terp-mainnet-api.itrocket.net:443",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
