/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "terra",
  displayName:
    "Terra Classic",
  website: null,
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/terra/images/luna.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/terra/images/luna.svg",
  },
  repository:
    "https://github.com/classic-terra/core",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/terra",
        "https://rpc.terrarebels.net",
        "https://terra-classic-rpc.publicnode.com",
        "https://rpc-terra-ia.cosmosia.notional.ventures/",
        "https://terraclassic-mainnet-rpc.autostake.com:443",
        "https://terraclassic-rpc-server-01.stakely.io",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/terra",
        "https://lcd.terrarebels.net",
        "https://terra-classic-lcd.publicnode.com",
        "https://api-terra-ia.cosmosia.notional.ventures/",
        "https://terraclassic-mainnet-lcd.autostake.com:443",
        "https://terraclassic-lcd-server-01.stakely.io",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      acrechain: {
        portId: "transfer",
        channelId:
          "channel-69",
        counterpartyChainId:
          "acrechain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-12",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-72",
        order: "unordered",
        version: "ics20-1",
      },
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-16",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-2",
        order: "unordered",
        version: "ics20-1",
      },
      juno: {
        portId: "transfer",
        channelId:
          "channel-20",
        counterpartyChainId:
          "juno",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-27",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-49",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-0",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
