/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "terra2",
  displayName: "Terra",
  website:
    "https://www.terra.money/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/terra2/images/luna.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/terra2/images/luna.svg",
  },
  repository:
    "https://github.com/terra-money/core/",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/terra2",
        "https://rpc.terrav2.ccvalidators.com:443/",
        "https://terra2-rpc.lavenderfive.com:443",
        "https://terra-rpc.polkachu.com",
        "https://terra-rpc.stakely.io:443/",
        "https://rpc-terra2.whispernode.com:443",
        "https://terra-mainnet-rpc.autostake.com:443",
        "https://phoenix-rpc.terra.dev:443",
        "https://terra-rpc.publicnode.com",
        "https://rpc-terra-01.stakeflow.io",
        "https://terra-phoenix-rpc.highstakes.ch:26657/",
        "https://rpc-terra.wildsage.io",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/terra2",
        "https://lcd-terra.wildsage.io",
        "https://terra-mainnet-lcd.autostake.com:443",
        "https://lcd-terra2.whispernode.com:443",
        "https://phoenix-lcd.terra.dev:443",
        "https://terra-rest.publicnode.com",
        "terra2-api.lavenderfive.com:443",
        "https://api-terra-01.stakeflow.io",
        "https://terra-phoenix-api.highstakes.ch:1317/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      neutron: {
        portId:
          "wasm.terra1jhfjnm39y3nn9l4520mdn4k5mw23nz0674c4gsvyrcr90z9tqcvst22fce",
        channelId:
          "channel-167",
        counterpartyChainId:
          "neutron",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-5",
        order: "unordered",
        version: "ics20-1",
      },
      carbon: {
        portId: "transfer",
        channelId:
          "channel-36",
        counterpartyChainId:
          "carbon",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-12",
        order: "unordered",
        version: "ics20-1",
      },
      stride: {
        portId: "transfer",
        channelId:
          "channel-46",
        counterpartyChainId:
          "stride",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-52",
        order: "unordered",
        version: "ics20-1",
      },
      migaloo: {
        portId: "transfer",
        channelId:
          "channel-86",
        counterpartyChainId:
          "migaloo",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-0",
        order: "unordered",
        version: "ics20-1",
      },
      acrechain: {
        portId: "transfer",
        channelId:
          "channel-77",
        counterpartyChainId:
          "acrechain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-9",
        order: "unordered",
        version: "ics20-1",
      },
      secretnetwork: {
        portId: "transfer",
        channelId:
          "channel-3",
        counterpartyChainId:
          "secretnetwork",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-16",
        order: "unordered",
        version: "ics20-1",
      },
      noble: {
        portId: "transfer",
        channelId:
          "channel-151",
        counterpartyChainId:
          "noble",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-9",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-1",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-251",
        order: "unordered",
        version: "ics20-1",
      },
      mars: {
        portId: "transfer",
        channelId:
          "channel-78",
        counterpartyChainId:
          "mars",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-2",
        order: "unordered",
        version: "ics20-1",
      },
      stafihub: {
        portId: "transfer",
        channelId:
          "channel-204",
        counterpartyChainId:
          "stafihub",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-9",
        order: "unordered",
        version: "ics20-1",
      },
      crescent: {
        portId: "transfer",
        channelId:
          "channel-37",
        counterpartyChainId:
          "crescent",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-27",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
