/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "thorchain",
  displayName: "THORChain",
  website:
    "https://thorchain.org/",
  logo: {
    png: null,
    svg: null,
  },
  repository:
    "https://gitlab.com/thorchain/thornode",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/thorchain",
        "https://btc.thorchain.info",
        "https://bch.thorchain.info",
        "https://ltc.thorchain.info",
        "https://bnb.thorchain.info",
        "https://eth.thorchain.info",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/thorchain",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
