/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "ununifi",
  displayName: "UnUniFi",
  website:
    "https://ununifi.io/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/ununifi/images/ununifi.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/ununifi/images/ununifi.svg",
  },
  repository:
    "https://github.com/UnUniFi/chain",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/ununifi",
        "http://a.lcd.ununifi.cauchye.net:26657",
        "http://b.lcd.ununifi.cauchye.net:26657",
        "http://ununifi.mainnet.lcd-01.kabab.io:26657",
        "http://ununifi.mainnet.lcd-02.kabab.io:26657",
        "https://ununifi-mainnet-rpc.autostake.com:443",
        "https://rpc.ununifi.nodestake.top",
        "https://rpc-ununifi.nodeist.net",
        "https://ununifi-rpc.lavenderfive.com:443",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/ununifi",
        "https://a.lcd.ununifi.cauchye.net:1318",
        "https://b.lcd.ununifi.cauchye.net:1318",
        "https://ununifi.mainnet.lcd-01.kabab.io:1318",
        "https://ununifi-mainnet-lcd.autostake.com:443",
        "https://ununifi.mainnet.lcd-02.kabab.io:1318",
        "https://api.ununifi.nodestake.top",
        "https://api-ununifi.nodeist.net",
        "https://ununifi-api.lavenderfive.com:443",
      ],
    },
  },
  evm: null,
  ibc: {},
} as const;
