/**
 * This file is auto-generated by the @nancyjs/registry package.
 */
export default {
  name: "vidulum",
  displayName: "Vidulum",
  website:
    "https://vidulum.app/",
  logo: {
    png: "https://raw.githubusercontent.com/cosmos/chain-registry/master/vidulum/images/vdl.png",
    svg: "https://raw.githubusercontent.com/cosmos/chain-registry/master/vidulum/images/vdl.svg",
  },
  repository:
    "https://github.com/vidulum/mainnet",
  tendermint: {
    api: {
      "jsonrpc-http": [
        "https://rpc.cosmos.directory/vidulum",
        "https://mainnet-rpc.vidulum.app/",
        "https://rpc-vidulum-ia.cosmosia.notional.ventures/",
        "https://rpc-vdl.nodine.id",
      ],
    },
  },
  cosmossdk: {
    api: {
      rest: [
        "https://rest.cosmos.directory/vidulum",
        "https://mainnet-lcd.vidulum.app",
        "https://api-vidulum-ia.cosmosia.notional.ventures/",
        "https://api-vdl.nodine.id/",
      ],
    },
  },
  evm: null,
  ibc: {
    channels: {
      okexchain: {
        portId: "transfer",
        channelId:
          "channel-11",
        counterpartyChainId:
          "okexchain",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-37",
        order: "unordered",
        version: "ics20-1",
      },
      osmosis: {
        portId: "transfer",
        channelId:
          "channel-0",
        counterpartyChainId:
          "osmosis",
        counterpartyPortId:
          "transfer",
        counterpartyChannelId:
          "channel-124",
        order: "unordered",
        version: "ics20-1",
      },
    },
  },
} as const;
